n = input('Digite algo ')
print('O tipo primitivo desse valor é ', type(n))
print('Só tem espaço', n.isspace())
print('É um número', n.isnumeric())
print('É alfabetico', n.isalpha())
print('É alfanumerico', n.isalnum())
print('Está em maiusculo', n.isupper())
print('Está em minusculo', n.islower())
print('Está capitalizada', n.istitle())

