numero = int(input('Digite um número de 0 a 9999 '))
num = str(numero)
print('Analisando o número {}'.format(num))
novo = num.rjust(4, '0')
print(novo)
print('Unidade: {}'.format(novo[3]))
print('Dezena: {}'.format(novo[2]))
print('Centena: {}'.format(novo[1]))
print('Milhar: {}'.format(novo[0]))
